### ISSUE TITLE
no papier en karton info from hvc

### ISSUE THREAD

**Issue by pathia** [cyberjunky/home-assistant-hvcgroep#11]
I've been using this custom integration for years but since last friday it started misbehaving.
It looks like the hvc api is not returning a date for collecting papier en karton anymore. 
The ophaaldatum field is null. 
I'm unsure how can I ask other hvc integration users if they have the same problem, so I thought let's create an issue for this.

**Comment by cyberjunky** [comment]
@pathia can you share debug data? I just checked and it still seem to work here as far as i can see

**Comment by pathia** [comment]
@cyberjunky I was just about to setup debugging and then found out that it started working again since yesterday just before midnight (while I was asleep for a hour, so nothing changed on my end)
So I guess the ticket can be closed. Nevertheless thanks for replying and of course for the integration as a whole! 👍
