### ISSUE TITLE
README shows incorrect names for sensors

### ISSUE THREAD

**Issue by mcmd1962** [cyberjunky/home-assistant-hvcgroep#14]
The sensors were not available when I was following the instructions in the README file. To make it work I had to change the names of the mentioned sensors. E.g. for plastic I changed it from _sensor.hvc_groep_plastic_ to _sensor.hvc_groep_plastic_en_verpakking_ in groups.yaml and configuration.yamls
Similar for the other sensors.

**Comment by cyberjunky** [comment]
Thanks for reporting, fixed in next README version!
