### ISSUE TITLE
Day attribute returns null in sensor

### ISSUE THREAD

**Issue by Neejoh** [cyberjunky/home-assistant-hvcgroep#2]
Lately it hasn't been working for me. I think this is because the `day` is always set to `null`, not to `morgen` where the template would show it in the frontend. 

In the developer tools I see the following for all `hvc_groep_*` sensors:

Entity: `sensor.hvc_groep_gft`
State: `04-09-2020`
Attributes: 
```
day: null
friendly_name: HVC Groep_gft
icon: mdi:food-apple-outline
```

Any idea what's going on here?

**Comment by cyberjunky** [comment]
Which Postal code are you in? I cannot reproduce it yet.

**Comment by Neejoh** [comment]
It seems to be working again now.
Not sure what the cause was, might have been a bug/problem with the Home Assistant beta I'm running. 

I'll report back in when it happens again any time soon.
