### ISSUE TITLE
Unknown dates

### ISSUE THREAD

**Issue by rednasss** [cyberjunky/home-assistant-hvcgroep#4]
I have been using this integration for a while, but I have some problems with it sometimes and then it shows this:
![hassio-HVC](https://user-images.githubusercontent.com/3071416/104896038-e9e45380-5976-11eb-9c33-78b59e691d68.PNG)
Do you know how I can fix this or should it be fixed on the integration side?
Thanks in advance!

**Comment by cyberjunky** [comment]
@rednasss Which postal code?

**Comment by rednasss** [comment]
1761JM!

**Comment by cyberjunky** [comment]
@rednasss It works here with huisnummmer 2, an invalid huisnummer like 1 gives the result onbekend for all sensors.
Also check your home assistant log.

Can you try this page with your huisnummer?
https://www.hvcgroep.nl/zelf-regelen/afvalkalender

**Comment by rednasss** [comment]
Yes, I already tried it and it works with my huisnummer. 
Most of the times it does work, but once in a while everything shows "Onbekend". Sometimes restarting fixes the problem, sometimes magic/time and sometimes it stays for a long time "Onbekend".
However, you don't know what could be causing it?

**Comment by cyberjunky** [comment]
@rednasss The question is, if you get the issue, does the calendar give valid data at the same time, maybe there are gaps, or invalid/non expecting data?
You can also enable debug mode to see what my integration think is going on, but I'm not sure if I output all data yet, can you try to see if that brings something in the log of HA? So like this:
https://github.com/cyberjunky/home-assistant-hvcgroep#debugging

**Comment by cyberjunky** [comment]
Closed because there hasn't been any activity on this issue recently. Please reopen if needed.

**Comment by martijnaikema** [comment]
I have the same issue sometimes. Usually it will work perfectly fine but sometimes I run in the same problems as described above also using HVC.

I looked at the logs and it has the following error:

2021-04-01 20:33:53 ERROR (MainThread) [custom_components.hvcgroep.sensor] 
Timeout occured while trying to get bagid from HVC

**Comment by cyberjunky** [comment]
@martijnaikema maybe the internet connection was shortly interrupted? Do you see other errors around this time? If not maybe the HVC site was not responding fast enough, we use a 5 second timeout on this request, shall we up it to 10?

**Comment by martijnaikema** [comment]
I also checked the HVC website just after receiving no result and that worked perfectly fine. If it happens again I will manually try to use the hvc API and see if that one works. It now is working again.
