### ISSUE TITLE
Logfile is filling with warning: implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by AbominableNoMan** [cyberjunky/home-assistant-hvcgroep#6]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:522 
First occurred: 13:59:40 (228 occurrences) 
Last logged: 14:27:40

Entity sensor.hvc_groep_gft (<class 'custom_components.hvcgroep.sensor.TrashSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.hvc_groep_plastic (<class 'custom_components.hvcgroep.sensor.TrashSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.hvc_groep_papier (<class 'custom_components.hvcgroep.sensor.TrashSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.hvc_groep_restafval (<class 'custom_components.hvcgroep.sensor.TrashSensor'>) implements device_state_attributes. Please report it to the custom component author.

Any ideas?

**Comment by cyberjunky** [comment]
Fixed in latest version, thanks!
