### ISSUE TITLE
sensors not getting values

### ISSUE THREAD

**Issue by FGOD1983** [cyberjunky/home-assistant-hvcgroep#7]
I installed this today, but somehow I am unable to get any ouput from the sensors.

From what I see in the logs it is due to the url now working or maybe changed from the HVC website/API:

```
Logger: custom_components.hvcgroep.sensor
Source: custom_components/hvcgroep/sensor.py:118
Integration: hvcgroep ([documentation](https://github.com/cyberjunky/home-assistant-hvcgroep), [issues](https://github.com/cyberjunky/home-assistant-hvcgroep/issues))
First occurred: 11:36:58 (1 occurrences)
Last logged: 11:36:58

Timeout occured while trying to get bagid from HVC
```
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.hvcgroep.sensor
Source: custom_components/hvcgroep/sensor.py:173
Integration: hvcgroep (documentation, issues)
First occurred: 11:37:04 (1 occurrences)
Last logged: 11:37:04

Timeout occured while trying to connect to HVC
```

**Comment by ronaldtveen** [comment]
I have not tested this but you could try this [repo/custom_component](https://github.com/marius1/home-assistant-custom-components), it uses the same HVC API.

At least you know if it's this component or a conflict between the HVC API and your instance.

**Comment by cyberjunky** [comment]
Closing since stale, please reopen if this is still an issue.
