### ISSUE TITLE
[feature request] Cleaning of GFT bins

### ISSUE THREAD

**Issue by tengels** [cyberjunky/home-assistant-hvcgroep#8]
As this is the most infrequent thing happening I always end up finding out afterwards that I should not have taken the GFT bin back to the house as it will mean the bin is not being cleaned.

The information on when the bins are cleaned is provided via their web interface (afvalstroom 59). Would it be possible to add this event to the current integration?

**Comment by cyberjunky** [comment]
@tengels better late then never, but can you try version 1.0.8 (add - reiniging to config)
I could not test since I don't have afvalstroom 59 in my data

**Comment by cyberjunky** [comment]
@tengels Do you now a postal code with reiniging afvalstroom (not your own preferably)

**Comment by tengels** [comment]
Tough luck :-)
We just received a letter indicating the cleaning service will be stopped (too expensive).

**Comment by cyberjunky** [comment]
Ok, the cleaning bins feature is in the code for some time.
Just add '- reiniging' to resources cfg entry to see if it works would be nice, if service is already stopped or you have no time, fine as well, no problem.
